name: Pull request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-package: jdk
          java-version: 21
          cache: maven
      - name: Build
        run: mvn -Pdelombok -B fmt:check package test-compile -DskipTests -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: "**/*"
          compression-level: 9
  test:
    needs: build
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 11,17,21 ]
        db: [ nodb,mysql5,mysql8,postgres,oracle18,oracle21,mssqlserver ]
      fail-fast: false
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: .
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-package: jdk
          java-version: ${{ matrix.jdk }}
          cache: maven
      - name: test
        run: mvn -Pconcise,noformat,only-${{ matrix.db }}-tests -B test -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
